version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pricepilot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/pricepilot
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./scrapers:/app/scrapers
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3001

volumes:
  postgres_data: